# -*- coding: utf-8 -*-
"""Golden end-to-end corpus (audit plan step 9).

One exact-output pin per verified behavior across every handler category.
If a handler change breaks a line here, the change regressed real output:
update a pin only when the NEW reading is deliberately better, never to
make a failure go away.

Regenerate candidates with the audit probe pattern: run each input through
``normalize`` and review every output by hand before pinning it.
"""

import pytest

from indic_normalizer import normalize

# (input, kwargs, exact expected output)
GOLDEN = [
    ('in 1947 India', {}, 'in nineteen forty seven India'),
    ('1,947 soldiers', {}, 'one thousand nine hundred and forty seven soldiers'),
    ('by 2025 end', {}, 'by twenty twenty five end'),
    ('in 2000 was Y2K', {}, 'in two thousand was Y two K'),
    ('0 items and 007', {}, 'zero items and zero zero seven'),
    ('dial 0091 first', {}, 'dial zero zero nine one first'),
    ('1939-1945 war', {}, 'nineteen thirty nine to nineteen forty five war'),
    ('pages 10-15', {}, 'pages ten to fifteen'),
    ('10-15% growth', {}, 'ten to fifteen percent growth'),
    ('carry 5-10 kg only', {}, 'carry five to ten kilograms only'),
    ('FY 2024-25 results', {}, 'FY twenty twenty four to twenty five results'),
    ('won 3:2 against them', {}, 'won three to two against them'),
    ('a 16:9 screen', {}, 'a sixteen to nine screen'),
    ('I paid $5 and she paid $10 yesterday.', {}, 'I paid five dollars and she paid ten dollars yesterday.'),
    ('₹1,23,45,678 raised', {}, 'one crore twenty three lakh forty five thousand six hundred and seventy eight rupees raised'),
    ('₹5 lakh was sanctioned', {}, 'five lakh rupees was sanctioned'),
    ('Rs 2.5 crore budget', {}, 'two point five crore rupees budget'),
    ('a ₹1 coin', {}, 'a one rupee coin'),
    ('₹0.50 candy', {}, 'fifty paise candy'),
    ('₹1.01 exactly', {}, 'one rupee and one paisa exactly'),
    ('Loss of ₹-500', {}, 'Loss of minus five hundred rupees'),
    ('₹99.00 only', {}, 'ninety nine rupees only'),
    ('last 5 years 2020 was worst', {}, 'last five years twenty twenty was worst'),
    ('two hours 30 minutes', {}, 'two hours thirty minutes'),
    ('Growth was 12.5% this year', {}, 'Growth was twelve point five percent this year'),
    ('-12% dip', {}, 'minus twelve percent dip'),
    ('5kg and 10 km and 37.5°C', {}, 'five kilograms and ten kilometers and thirty seven point five degrees celsius'),
    ('-5°C in Leh', {}, 'minus five degrees celsius in Leh'),
    ('6ft tall', {}, 'six feet tall'),
    ('5 GB data and 2 MB file', {}, 'five gigabytes data and two megabytes file'),
    ('15/08/1947 was independence', {}, 'fifteenth August nineteen forty seven was independence'),
    ('Meeting on 2024-03-05', {}, 'Meeting on fifth March twenty twenty four'),
    ('08/15/1947 anniversary', {}, 'fifteenth August nineteen forty seven anniversary'),
    ('15 August 1947 dawn', {}, 'fifteenth August nineteen forty seven dawn'),
    ('Aug 15, 1947 issue', {}, 'August fifteenth nineteen forty seven issue'),
    ('meeting on 5 June', {}, 'meeting on fifth June'),
    ('born 2nd October 1869', {}, 'born second October eighteen sixty nine'),
    ('March 2020 lockdown', {}, 'March twenty twenty lockdown'),
    ('Train at 18:45', {}, 'Train at eighteen forty five'),
    ('at 10:30:45 sharp', {}, 'at ten thirty forty five sharp'),
    ('Meeting at 10:30 am on 15/08/1947', {}, 'Meeting at ten thirty am on fifteenth August nineteen forty seven'),
    ('meeting 10:30 am. Done.', {}, 'meeting ten thirty am. Done.'),
    ('the 1990s music', {}, 'the nineteen nineties music'),
    ('back in the 90s era', {}, 'back in the nineties era'),
    ('Call +91 98765 43210 now', {}, 'Call plus nine one nine eight seven six five four three two one zero now'),
    ('Call 98765 43210', {}, 'Call nine eight seven six five four three two one zero'),
    ('Call 011-2345-6789', {}, 'Call zero one one two three four five six seven eight nine'),
    ('Aadhaar 1234 5678 9012', {}, 'Aadhaar one two three four five six seven eight nine zero one two'),
    ('years 2020 2021 were tough', {}, 'years twenty twenty twenty twenty one were tough'),
    ('scores 100 200 300 today', {}, 'scores one hundred two hundred three hundred today'),
    ('agent 007 reporting', {}, 'agent zero zero seven reporting'),
    ('3/4 of the cake', {}, 'three quarters of the cake'),
    ('24/7 support', {}, 'twenty four over seven support'),
    ('pi is 3.14', {}, 'pi is three point one four'),
    ('temp -3.5 degrees', {}, 'temp minus three point five degrees'),
    ('1,234.56 total', {}, 'one thousand two hundred and thirty four point five six total'),
    ('pi is 3.14159265358979', {}, 'pi is three point one four one five nine two six five three five eight nine seven nine'),
    ('Python 3.11.4 released', {}, 'Python three point eleven point four released'),
    ('server 192.168.1.1 up', {}, 'server one nine two dot one six eight dot one dot one up'),
    ('He came 21st in the 3rd race', {}, 'He came twenty first in the third race'),
    ('COVID19 and 5G and MP3', {}, 'COVID nineteen and five G and MP three'),
    ('+42 improvement', {}, 'plus forty two improvement'),
    ('−42 today', {}, 'minus forty two today'),
    ('mail test123@gmail.com now', {}, 'mail test one two three at gmail dot com now'),
    ('visit www.example.com/page2 today', {}, 'visit w w w dot example dot com slash page two today'),
    ('on flipkart.in sale', {}, 'on flipkart dot in sale'),
    ('Go to example.com.', {}, 'Go to example dot com.'),
    ('e.g. this and etc. stay', {}, 'for example this and et cetera stay'),
    ('2 + 2 = 4', {}, 'two plus two equals four'),
    ('Johnson & Johnson', {}, 'Johnson and Johnson'),
    ('meet @ 5', {}, 'meet at five'),
    ('5 < 10 and 20 > 15', {}, 'five less than ten and twenty greater than fifteen'),
    ('great :) 42 done', {}, 'great :) forty two done'),
    ('text (remove (this) too) kept', {}, 'text kept'),
    ('a ( b 42', {}, 'a ( b forty two'),
    ("Hello [pause] <break time='1s'/> world 42", {}, "Hello [pause] <break time='1s'/> world forty two"),
    ('Line one\\nLine two\\there', {}, 'Line one Line two here'),
    ('Solve $x^2+2x+1=0$ now', {}, 'Solve x squared plus two x plus one equals zero now'),
    ('cost $5 and $x+y$ math', {}, 'cost five dollars and x plus y math'),
    ('let $n$ be even', {}, 'let n be even'),
    ('Water is \\ce{H2O}', {}, 'Water is H two O'),
    ('भारत 1947 में', {'lang': 'hi'}, 'भारत nineteen forty seven में'),
    ('यह १९४७ की बात है।', {'lang': 'hi'}, 'यह एक हज़ार नौ सौ सैंतालीस की बात है।'),
    ('१५/८/१९४७ को', {'lang': 'hi'}, 'पंद्रह अगस्त एक हज़ार नौ सौ सैंतालीस को'),
    ('५०% छूट', {'lang': 'hi'}, 'पचास प्रतिशत छूट'),
    ('१२.५% वृद्धि', {'lang': 'hi'}, 'बारह दशमलव पाँच प्रतिशत वृद्धि'),
    ('5वाँ स्थान', {'lang': 'hi'}, 'पाँचवाँ स्थान'),
    ('१०-१५ लोग', {'lang': 'hi'}, 'दस से पंद्रह लोग'),
    ('₹५ लाख की लागत', {'lang': 'hi'}, 'पाँच लाख रुपये की लागत'),
    ('३.१४ का मान', {'lang': 'hi'}, 'तीन दशमलव एक चार का मान'),
    ('5वा क्रमांक', {'lang': 'mr'}, 'पाचवा क्रमांक'),
    ('3তম পুরস্কার', {'lang': 'bn'}, 'তৃতীয় পুরস্কার'),
    ('௧௨௩ புத்தகங்கள்', {'lang': 'ta'}, 'நூற்று இருபத்து மூன்று புத்தகங்கள்'),
    ('১৯৪৭ সালে', {'lang': 'bn'}, 'এক হাজার নশো সাতচল্লিশ সালে'),
    ('۱۹۴۷ میں', {'lang': 'ur'}, 'ایک ہزار نو سو سینتالیس میں'),
    ('1234', {'lang': 'te', 'force': True}, 'ఒక వెయ్యి రెండు వందల ముప్పై నాలుగు'),
    ('Dr. Sharma met Mr. Rao', {}, 'Doctor Sharma met Mister Rao'),
    ('Tata Pvt. Ltd. filed', {}, 'Tata Private Limited filed'),
    ('India vs. Australia', {}, 'India versus Australia'),
    ('St. Xavier lives on Main St. nearby', {}, 'Saint Xavier lives on Main Street nearby'),
    ('U.S.A. and B.J.P. won', {}, 'U S A and B J P won'),
    ('PAN ABCDE1234F given', {}, 'PAN A B C D E one two three four F given'),
    ('car KA 01 AB 1234 parked', {}, 'car K A zero one A B one two three four parked'),
    ('PIN 560001 area', {}, 'PIN five six zero zero zero one area'),
    ('2 करोड़ लोग', {'lang': 'hi'}, 'दो करोड़ लोग'),
    ('on 15.8.1947 India', {}, 'on fifteenth August nineteen forty seven India'),
    ('energy 1.5e10 joules', {}, 'energy one point five times ten to the power ten joules'),
    ('Chapter IV begins', {}, 'Chapter four begins'),
    ('Class X results', {}, 'Class ten results'),
    ('during World War II era', {}, 'during World War two era'),
    ('India 287/5 in 50 overs', {}, 'India two hundred and eighty seven for five in fifty overs'),
    ('BP was 140/90 mmHg today', {}, 'BP was one hundred and forty over ninety millimeters of mercury today'),
    ('Ms. Rao and Mrs. Iyer', {}, 'Miz Rao and Missus Iyer'),
    ('fee 99.50₹ paid', {}, 'fee ninety nine rupees and fifty paise paid'),
    ('gave 100 rs. today', {}, 'gave one hundred rupees today'),
    ('battery 5000 mAh lasts', {}, 'battery five thousand milliamp hours lasts'),
    ('wifi at 2.4 GHz and 5 GHz', {}, 'wifi at two point four gigahertz and five gigahertz'),
    ('3000 rpm motor used 1.5 kWh', {}, 'three thousand revolutions per minute motor used one point five kilowatt hours'),
    ("MG St and St. Mary's on Main St.", {}, "MG Street and Saint Mary's on Main Street"),
    ('১৫/৮/১৯৪৭ সালে', {'lang': 'bn'}, 'পনেরো আগস্ট এক হাজার নশো সাতচল্লিশ সালে'),
    ('१५/८/१९४७ रोजी', {'lang': 'mr'}, 'पंधरा ऑगस्ट एक हज़ार नऊशे सत्तेचाळीस रोजी'),
    ('௧௫/௮/௧௯௪௭ அன்று', {'lang': 'ta'}, 'பதினைந்து ஆகஸ்ட் ஆயிரத்து தொள்ளாயிரத்து நாற்பத்து ஏழு அன்று'),
    ('۱۵/۸/۱۹۴۷ کو', {'lang': 'ur'}, 'پندرہ اگست ایک ہزار نو سو سینتالیس کو'),
    ('5ਵਾਂ ਦਿਨ', {'lang': 'pa'}, 'ਪੰਜਵਾਂ ਦਿਨ'),
    ('2واں', {'lang': 'ur'}, 'دوسرا'),
    ('₹५०.५०', {'lang': 'mai'}, 'पचास रुपये आ पचास पैसे'),
    ('flight 6E204 delayed', {}, 'flight six E two zero four delayed'),
    ('code AB123CD here', {}, 'code A B one two three C D here'),
    ('seat 32A', {}, 'seat thirty two A'),
    ('room 225 is ready', {}, 'room two twenty five is ready'),
    ('flight 6204 landed', {}, 'flight sixty two oh four landed'),
    ('The area is $\\int_0^1 x^2\\,dx$ which equals 1/3.', {}, 'The area is integral from zero to one of x squared d x which equals one third.'),
]


@pytest.mark.parametrize("text,kwargs,expected", GOLDEN)
def test_golden(text, kwargs, expected):
    assert normalize(text, **kwargs) == expected


@pytest.mark.parametrize("text,kwargs,expected", GOLDEN)
def test_idempotent(text, kwargs, expected):
    # normalizing already-normalized text must be a no-op
    assert normalize(expected, **kwargs) == expected
